/**
 * Parses raw Markdown text generated by AI into a structured JSON block array
 * tailored for the custom BlockRenderer frontend component.
 */
function parseMarkdownToBlocks(markdownStr) {
  if (!markdownStr) return [];

  // Remove YAML frontmatter if present (between '---' lines at start)
  let cleanMarkdown = markdownStr;
  if (cleanMarkdown.startsWith('---')) {
    const endOfYaml = cleanMarkdown.indexOf('---', 3);
    if (endOfYaml !== -1) {
      cleanMarkdown = cleanMarkdown.substring(endOfYaml + 3).trim();
    }
  }

  // Remove Title/H1 which is usually handled entirely by the article meta schema
  cleanMarkdown = cleanMarkdown.replace(/^#\s+.+$/m, '').trim();

  // Ensure headings have a blank line after them to prevent them from merging with paragraphs
  cleanMarkdown = cleanMarkdown.replace(/^(#{1,6}\s+.+)\n(?!\s*\n)/gm, '$1\n\n');

  // Split by double newlines to extract blocks
  const rawBlocks = cleanMarkdown.split(/\n\s*\n/);
  const structuredBlocks = [];

  for (let i = 0; i < rawBlocks.length; i++) {
    const rawBlock = rawBlocks[i].trim();
    if (!rawBlock) continue;

    const lowerBlock = rawBlock.toLowerCase();

    // Headings
    if (rawBlock.match(/^###\s+(.+)$/)) {
      structuredBlocks.push({
        type: 'heading',
        level: 3,
        text: rawBlock.replace(/^###\s+/, '').trim()
      });
      continue;
    }

    if (rawBlock.match(/^##\s+(.+)$/)) {
      structuredBlocks.push({
        type: 'heading',
        level: 2,
        text: rawBlock.replace(/^##\s+/, '').trim()
      });
      continue;
    }

    // Quotes
    if (rawBlock.startsWith('>')) {
      const quoteText = rawBlock.replace(/^>\s*/gm, '').trim();
      structuredBlocks.push({
        type: 'quote',
        text: quoteText
      });
      continue;
    }

    // Lists (Unordered or Ordered)
    if (rawBlock.match(/^(?:-|\*|\d+\.)\s+.+/m)) {
      const lines = rawBlock.split('\n');
      const items = lines
        .filter(line => line.trim().match(/^(?:-|\*|\d+\.)\s+/))
        .map(line => line.replace(/^(?:-|\*|\d+\.)\s+/, '').trim());
      
      if (items.length > 0) {
        structuredBlocks.push({
          type: 'list',
          items: items
        });
      }
      continue;
    }

    // Highlights (Heuristics for an important sentence wrapped in bold or having specific keywords)
    if (rawBlock.match(/^\*\*.*\*\*$/) && rawBlock.length > 20 && rawBlock.length < 150) {
        structuredBlocks.push({
            type: 'highlight',
            text: rawBlock.replace(/\*\*/g, '').trim()
        });
        continue;
    }

    // Standard Paragraphs
    structuredBlocks.push({
      type: 'paragraph',
      text: rawBlock
    });
  }

  // Filter out any blocks that ended up with empty text fields due to formatting issues
  return structuredBlocks.filter(block => {
    if (block.type === 'list') return block.items && block.items.length > 0;
    if (block.type === 'image') return !!block.url;
    if (block.text !== undefined) return block.text.trim().length > 0;
    return true;
  });
}

module.exports = { parseMarkdownToBlocks };
